/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#0F172A',
        'on-primary': '#FFFFFF',
        'primary-container': '#0F172A',
        'on-primary-container': '#FFFFFF',
        'inverse-on-surface': '#FFFFFF',
        secondary: '#115E59',
        'on-secondary': '#FFFFFF',
        'secondary-container': '#A8ECE5',
        'on-secondary-container': '#0F766E',
        'secondary-fixed': '#ABEFE8',
        'on-secondary-fixed': '#00201E',
        'secondary-fixed-dim': '#8FD3CC',
        tertiary: '#854D0E',
        'on-tertiary': '#FFFFFF',
        'tertiary-fixed': '#FFDCC0',
        'on-tertiary-fixed': '#2D1600',
        'tertiary-fixed-dim': '#FFB877',
        error: '#BA1A1A',
        'on-error': '#FFFFFF',
        'error-container': '#FFDAD6',
        'on-error-container': '#93000A',
        background: '#F8FAFC',
        'on-background': '#0B1C30',
        surface: '#F8FAFC',
        'on-surface': '#0F172A',
        'on-surface-variant': '#64748B',
        'surface-container-lowest': '#FFFFFF',
        'surface-container-low': '#F1F5F9',
        'surface-container': '#F1F5F9',
        'surface-container-high': '#E2E8F0',
        'surface-container-highest': '#CBD5E1',
        'surface-variant': '#E2E8F0',
        outline: '#94A3B8',
        'outline-variant': '#E2E8F0',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'gutter-xs': '0.25rem',
        'gutter-sm': '0.5rem',
        'gutter-md': '1rem',
        'gutter-lg': '1.5rem',
        'gutter-xl': '2rem',
        'screen-edge': '1.25rem',
        'card-pad': '1.25rem',
        'row-gap': '0.75rem',
      },
      fontFamily: {
        serif: ['Merriweather', 'Georgia', 'serif'],
        sans: ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'display-lg': ['Merriweather', 'Georgia', 'serif'],
        'headline-lg': ['Merriweather', 'Georgia', 'serif'],
        'headline-md': ['Merriweather', 'Georgia', 'serif'],
        'headline-sm': ['Merriweather', 'Georgia', 'serif'],
        'title-lg': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'title-md': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'body-lg': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'body-md': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'body-sm': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'label-lg': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'label-md': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        'label-sm': ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['26px', { lineHeight: '34px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'headline-md': ['21px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-sm': ['17px', { lineHeight: '24px', fontWeight: '700' }],
        'title-lg': ['18px', { lineHeight: '26px', fontWeight: '600' }],
        'title-md': ['15px', { lineHeight: '22px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '26px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '22px', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '18px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.03em', fontWeight: '600' }],
      },
      boxShadow: {
        sm: '0 1px 3px rgba(15, 23, 42, 0.04)',
        md: '0 10px 25px -5px rgba(15, 23, 42, 0.08), 0 8px 10px -6px rgba(15, 23, 42, 0.04)',
        xl: '0 10px 25px -5px rgba(15, 23, 42, 0.08), 0 8px 10px -6px rgba(15, 23, 42, 0.04)',
      },
    },
  },
  plugins: [],
}
